### ISSUE TITLE
Increase the roundness of rounded corners

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#10]
The app UI is all made of sharp-cornered elements, is it possible to implement rounded corners?

**Comment by huynhsontung** [comment]
Most of the controls already have 2px rounded corners (except `AppBarButton`) which follows WinUI's trend. Do you mean increase the roundness?

**Comment by MarcAnt01** [comment]
> Most of the controls already have 2px rounded corners (except `AppBarButton`) which follows WinUI's trend. Do you mean increase the roundness?

Oh, noticed now they were 2px, they looked totally sharp to me🙈

**Comment by MarcAnt01** [comment]
Anyway, I think it's better to increase the roundness, as it is now it's hard to be noticed

**Comment by huynhsontung** [comment]
This is intended to follow WinUI look and feel. No change is expected. Closing for now.
