### ISSUE TITLE
Feature Request: Add option to hide stories section?

### ISSUE THREAD

**Issue by 0xrpj** [huynhsontung/Indirect#100]
I want to hide this section in the application!

<img width="282" alt="image" src="https://user-images.githubusercontent.com/56220537/152647732-e9a48067-9f7d-4b23-bcd3-02cb215627ea.png">

**Comment by franciscoyira** [comment]
As a user, I would love this. Would be super helpful for when you just want to use the messaging functionality in a "distraction free" mode.

**Comment by huynhsontung** [comment]
Option added in v2.7.4 
![image](https://user-images.githubusercontent.com/31434093/171078325-38cb5752-b400-4aa5-bddc-a0789db87759.png)
