### ISSUE TITLE
Open stories and profile image from dialog

### ISSUE THREAD

**Issue by xperiandri** [huynhsontung/Indirect#102]
Could you add the ability to open stories (click) and a profile picture (Ctrl + click and context menu) from the profile icon

![image](https://user-images.githubusercontent.com/2365592/185258752-838bde17-643f-408d-9d2c-0904a26ca124.png)

**Comment by huynhsontung** [comment]
To clarify, you want to be able to open stories by:
- Ctrl + click and/or context menu on the profile picture in the thread title
- Click the profile picture in the View profile flyout

Did I get that right?

**Comment by xperiandri** [comment]
Correct

**Comment by huynhsontung** [comment]
Implemented in v2.8.0. When a user has a story reel, their profile picture will have an indicator and you can now click on it to see the story reel.
