### ISSUE TITLE
Indirect uses outdated WebView 1 (IE engine) for Facebook login

### ISSUE THREAD

**Issue by Kenya-West** [huynhsontung/Indirect#103]
To reproduce: 
1. Open the new app installed, sign out from account or perform a hard reset of the app, you choose 
2. Click **Sign in with Facebook**
3. See the message that this browser is outdated and not supported

This way to sign in can break at any moment, please use WebView 2 (Edge engine) to solve the problem

**Comment by huynhsontung** [comment]
Resolved in v2.7.6
