### ISSUE TITLE
download Link is inaccessible

### ISSUE THREAD

**Issue by Runixe786** [huynhsontung/Indirect#109]
The microsoft store link isnt working anymore, maybe its removed from the store. is there any other way we can download and install it?

**Comment by bathtimethiago** [comment]
http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/abc50d2a-288c-4bdc-a548-3a442570f60e?P1=1724349352&P2=404&P3=2&P4=UJXztcUSMZwrTHAW%2fxzP5IO%2fq8dZR%2bTFfjoiKavfz%2fa1Z3s1QoIetSA29LnZIwjv2TLCknpxi45%2fe4qvsglpGg%3d%3d

**Comment by huynhsontung** [comment]
I just added a new download link on the release page: [Indirect_2.9.0.0_neutral.msixbundle](https://github.com/huynhsontung/Indirect/releases/download/v2.9.0/Indirect_2.9.0.0_neutral.msixbundle)
