### ISSUE TITLE
Double click on a message to like it

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#11]

**Comment by huynhsontung** [comment]
This might complicate current flow like tap on image to enter `ImmersiveView`. I am considering it but for now you can like message by right click context menu.

**Comment by MarcAnt01** [comment]
> This might complicate current flow like tap on image to enter `ImmersiveView`. I am considering it but for now you can like message by right click context menu.

If you are interested you could take a look at Unigram code, it implements double tap to like (only over the bubble), but this behaviour is automatically disabled for photos

**Comment by huynhsontung** [comment]
Added in 0f7f92a170ecd11258fd1a324e1fd31fb49d9779
