### ISSUE TITLE
Ability to send and reproduce voice messages

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#13]

**Comment by MarcAnt01** [comment]
The ability to reproduce voice messages has been added at a certain point, but the ui is pretty ugly to me

**Comment by huynhsontung** [comment]
I guess you mean playing voice messages? That was already implemented a long time ago. The problem is sending one as I have not found a way to do this.

**Comment by huynhsontung** [comment]
The current UI for playing voice is the default MediaPlayerElement UI and it's something that takes a long time to style but the result might not be worth it. Priority for that is pretty low.

**Comment by shadwinful** [comment]
add the posibility to send voice message

**Comment by huynhsontung** [comment]
Finally added in 6bfd032ae4366518e4c1b40b3b371ab2c32c6c63 and 962d12e341c347e656514355fd56a59d066e731e
