### ISSUE TITLE
Delay in chats search

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#14]
The first time I look for a chat, it takes a bit to get auto-completion (2-3 seconds), after that if I close the search and do it once again the delay is no longer present

**Comment by huynhsontung** [comment]
Can't reproduce. Maybe network problem at the time?

**Comment by MarcAnt01** [comment]
> Can't reproduce. Maybe network problem at the time?

Nope, my network connection is OK and it's still happening, if you need I can give you access to my PC where you can debug the app
