### ISSUE TITLE
Automatically set the focus on typing bar when opening a chat

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#15]

**Comment by huynhsontung** [comment]
I tried so many ways but can't really achieve this

**Comment by huynhsontung** [comment]
Figured out a way to do this.
Added in 40de00e613002ca2883790603277a96392778ea9

**Comment by MarcAnt01** [comment]
Still not working deploying from develop

**Comment by huynhsontung** [comment]
It's hackish, it only works after you open a thread for the first time and not in compact mode
