### ISSUE TITLE
Show "Content not available because @urloftheuser has a hidden account" info

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#20]

**Comment by huynhsontung** [comment]
I need to somehow reproduce this as none of my contacts have hidden account or blocked

**Comment by huynhsontung** [comment]
added in 1105bfb5f3f01764fd2ae3c4d8f8f2af171f5bad

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/78422913-11c22f00-7663-11ea-8743-df7bbda73261.png)
That's what I see instead of a dialog

**Comment by MarcAnt01** [comment]
Still not working here

**Comment by huynhsontung** [comment]
Looking into it

**Comment by huynhsontung** [comment]
Forgot to copy `Placeholder` property from `DirectItem` source to wrapper. Fixed in a262ae2b598ea8af5ece60fabda735bef4f4d52a
