### ISSUE TITLE
Show videocalls activity

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#21]
I understand that videocalls implementation would be very difficult, but I'd be happy to have this type of activity displayed

**Comment by huynhsontung** [comment]
The app can already tell video call activity is happening but that's about it. I don't know if I can make it work or even worth investing time to implement video call feature.

**Comment by MarcAnt01** [comment]
> The app can already tell video call activity is happening but that's about it. I don't know if I can make it work or even worth investing time to implement video call feature.

You sure? That's what is displayed (it's a group)
![image](https://user-images.githubusercontent.com/43090263/77349470-5a144f80-6d3b-11ea-80d9-bd25f00877a3.png)

**Comment by huynhsontung** [comment]
Fixed in 108104caccc0f8f3bd7a92dad1b56e4e73b3b2ad
