### ISSUE TITLE
Utilize toast header to declutter notifications

### ISSUE THREAD

**Issue by huynhsontung** [huynhsontung/Indirect#26]
Details [here](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-headers)

**Comment by MarcAnt01** [comment]
@huynhsontung it could be good also to add the possibility to reply to a message directly from the notification

**Comment by huynhsontung** [comment]
Yes I do plan to have that too but it's kinda low on priority right now. Maybe it will make it before v1.0 but I'm not sure. Thanks for bringing that up 👍

**Comment by huynhsontung** [comment]
Done in 7a1ee593c7d33511355c27a7f3ae42ac53ef7193
