### ISSUE TITLE
Possibility to reply to a message through notifications

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#28]

**Comment by huynhsontung** [comment]
~~Windows 10 notifications handling is really bad compared to other platforms. This was on my todo list but I am testing some rapid notifications that will sadly conflict with this feature. More details about this soon!~~
This feature was reverted in v1.4.0 since it was too buggy.

**Comment by huynhsontung** [comment]
This is implemented in v1.4.1
![image](https://user-images.githubusercontent.com/31434093/93651877-df657d80-f9c7-11ea-99c7-fa58fe9a532a.png)
