### ISSUE TITLE
What's the function of the button marked in green?

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#31]
![image](https://user-images.githubusercontent.com/43090263/77856039-ca681880-71f4-11ea-96e4-cd4034f9a10e.png)

**Comment by huynhsontung** [comment]
It's for creating a new chat thread. Right now the search feature serves the same purpose so I if you click on it will focus to the search box. In the future I want to add ability to create group chat using that button.

**Comment by huynhsontung** [comment]
Create new thread feature is now fully implemented in 845660cf2983e977d48d6bc7b1ea0b596d5341e8

**Comment by huynhsontung** [comment]
This should also close #32
