### ISSUE TITLE
Removed story

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#35]
Show activity when sending a story that has been removed later

**Comment by huynhsontung** [comment]
Do you have an image reference for this?

**Comment by MarcAnt01** [comment]
> Do you have an image reference for this?

Image of what official apps do show or some help to reproduce it?

**Comment by huynhsontung** [comment]
Yes. Screenshots from the official app would be the best.

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/83680068-b66bd900-a5e0-11ea-8261-44806c01b48d.png)

**Comment by huynhsontung** [comment]
Implemented in version 1.0.3
