### ISSUE TITLE
Since the update with stories I can't see directs any longer

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#41]
![image](https://user-images.githubusercontent.com/43090263/82116077-34b62780-9767-11ea-93c5-4d9e5383d7c9.png)

**Comment by huynhsontung** [comment]
Oh wow. Have you try reset/reinstall the app?

**Comment by MarcAnt01** [comment]
Hi Tung, as expected nothing changed

**Comment by MarcAnt01** [comment]
This has been fixed with latest commits
