### ISSUE TITLE
Grey tile in start menu

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#43]
Microsoft is making grey the tiles of its UWPs, so why not doing the same with Indirect? With the current icon it'd look even better to me

**Comment by huynhsontung** [comment]
Ah good idea! I haven't paid much attention to the tile lately.

**Comment by MarcAnt01** [comment]
#404040
That's the code to have the same grey as ToDo and Office

**Comment by huynhsontung** [comment]
Added in 7e684903bcca93bb73ffdb96469c29da1cae08ca
