### ISSUE TITLE
Webview Preview for extern links

### ISSUE THREAD

**Issue by lorisobi** [huynhsontung/Indirect#45]
![Preview](https://user-images.githubusercontent.com/28399150/83350315-a8495e80-a33b-11ea-9c05-64f816e6e6a8.jpg)

When you click on links like "Show Profile" the app redirects to the browser which is ok. But I think it would be more user friendly when the Indirect could show a preview (webview in flyout) of the webpage on hover before clicking. 

![image](https://user-images.githubusercontent.com/28399150/83350369-e8104600-a33b-11ea-87cd-29e4f1b9b1fd.png)

This should be similar to the preview feature in wikipedia but only made with a simple webview in a flyout.

**Comment by MarcAnt01** [comment]
Afaik I prefer to have external links to open in the browser for a desktop app

**Comment by lorisobi** [comment]
of course **open** - but before you click the app could show a preview on hover

**Comment by MarcAnt01** [comment]
Ah, so just on mouse hover. I don't think this UI is good and sounds an overkill to me

**Comment by huynhsontung** [comment]
Instagram already provides link previews when sharing link in messages.

![image](https://user-images.githubusercontent.com/31434093/83371181-91742d80-a376-11ea-8ed6-d25eb8e0813d.png)

Webview preview sounds cool on paper but it's not very nice UX in practice. Web pages don't load instantly, sites like Instagram takes tons of time and resources to load, which makes the app consume more memory, and CPU. Current Webview implementation runs everything on UI thread so it may actually hurt overall responsiveness.

From the mock you provided, I think what you want is some quick info about the user like full name, description, friendship status, etc. when you hover on Profile button. This is possible to do without using Webview at all. 

Let me know what you think.

**Comment by lorisobi** [comment]
> From the mock you provided, I think what you want is some quick info about the user like full name, description, friendship status, etc. when you hover on Profile button. This is possible to do without using Webview at all.

This sounds great.

**Comment by huynhsontung** [comment]
This feature has been implemented in v0.12.7

![image](https://user-images.githubusercontent.com/31434093/83955913-07601500-a80d-11ea-8b96-a4885b7cf8c4.png)
