### ISSUE TITLE
Please Add Ability to Have Multiple Accounts Logged in at Once

### ISSUE THREAD

**Issue by thegalantblog** [huynhsontung/Indirect#46]
I've absolutely fallen in love with this app and its design! It is so well put together. I can definitely see myself using this more than the actual Instagram app on my phone! To be honest with you I only really use Instagram for DMs and viewing stories, which is exactly what this app does! Right now though, with this app, I can only be signed into one account at a time. And when I log out, it doesn't remember me so I have to re-login. I currently have three Instagram accounts that I use for messaging with others. _It would be really useful and great if I could have multiple accounts logged in at once and have the ability to switch between my accounts without having to keep logging out and logging back in._

Thank you so much again for all the hard work you have put into this app, I really hope you will be willing to look into my feedback and possibly add this feature in the future :)

**Comment by huynhsontung** [comment]
Thank you for your kind words 🥰

The ability to have multiple accounts is something I really have not considered before. I can definitely see the benefits having this feature. However, since this change would require a considerable amount of rework to the application flow, I don't think it will be done anytime soon. But fret not, it is definitely on my backlog 👍

**Comment by thegalantblog** [comment]
Of course, I want you know that your hard work has not gone unappreciated😊! 

I definitely understand, and I'm fine with waiting😊! Even if it never comes, I'll still be using Indirect🤠😤✊🏾, I never knew just how much I needed it into a saw it on an article a couple days ago😂.

**Comment by huynhsontung** [comment]
Feature added in v2.0
