### ISSUE TITLE
Mark unseen stories

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#47]
In stories section there's no way to understand if a story has been seen or not. Official app shows a circle around the ones that haven't been seen

**Comment by huynhsontung** [comment]
This is true. I am aware of this problem but this feature has to wait until after I finished with #39

**Comment by huynhsontung** [comment]
Implemented in version 1.2.0.

![image](https://user-images.githubusercontent.com/31434093/86082191-02793480-ba4c-11ea-9d15-681a864f2d3e.png)
