### ISSUE TITLE
Messages with posts are sometimes cut out

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#49]
![image](https://user-images.githubusercontent.com/43090263/85027429-374ad900-b17a-11ea-8421-75a4d38cc242.png)

**Comment by huynhsontung** [comment]
Instagram post in message is meant to be a preview only. To see the full post you have to click on the message itself and it will open the web version of the post. That being said, I can see why this intention is not clear and is definitely an UI/UX problem. I will look into it.

**Comment by huynhsontung** [comment]
![CPNT5R3tst](https://user-images.githubusercontent.com/31434093/85217385-05d23900-b345-11ea-9be9-8df55b4dcdd8.gif)

This is addressed in version v1.1.0. Let me know what you think.

**Comment by MarcAnt01** [comment]
I don't like it, it would force people to scroll when there's enough space in the chat

**Comment by huynhsontung** [comment]
Hmm fair point. We have a nested scrollbars situation here. UX wise this is also not ideal. Oh well full height caption it is.

**Comment by huynhsontung** [comment]
![image](https://user-images.githubusercontent.com/31434093/85233250-c72a9600-b3b9-11ea-8882-a680ae7bd4c9.png)
And fixed! Also carousel posts will now display the first image and number of photos in the carousel.

**Comment by MarcAnt01** [comment]
Thanks, closing the issue
