### ISSUE TITLE
Integrate with Contacts and My People

### ISSUE THREAD

**Issue by xperiandri** [huynhsontung/Indirect#50]

**Comment by huynhsontung** [comment]
Sadly My People feature [is deprecated](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features) so I don't think I will make any support for it.

**Comment by xperiandri** [comment]
But it works

**Comment by xperiandri** [comment]
What about contacts integration?

**Comment by huynhsontung** [comment]
Instagram doesn't provide enough information to merge contacts afaik. You would have contact entities with just Instagram username and full name. Considering it's a hassle to keep those contacts in sync with Instagram, I frankly don't see the benefits of doing that.

As for My People, it's generally a bad idea to implement deprecated feature, especially when it's going to massively change the codebase. It looks really interesting but I just don't have the capacity to take on this change.

**Comment by MarcAnt01** [comment]
My people also is hidden by default on Windows 10 now, I don't think it's worthy to spend time on it

**Comment by xperiandri** [comment]
It does not differ from opening a new view in Unigram.
If Indirect does not support more than one view and will not, that I could agree.

**Comment by MarcAnt01** [comment]
Unigram syncs contacts with Windows, there's no such thing for Instagram

**Comment by xperiandri** [comment]
@MarcAnt01 this is the most important feature that I need!

**Comment by MarcAnt01** [comment]
I understand you need this feature, but you're using it as it's not designed to be used

**Comment by xperiandri** [comment]
Why Instagram user can't be a contact?

**Comment by huynhsontung** [comment]
```json
"user": {
        "pk": 1111111111,
        "username": "johndoe",
        "full_name": "John Doe",
        "is_private": true,
        "profile_pic_url": "https://instagram.fyvr4-1.fna.fbcdn.net/...",
        "profile_pic_id": "...",
        "is_verified": false,
        "has_anonymous_profile_picture": false,
        "media_count": 315,
        "geo_media_count": 0,
        "follower_count": 156,
        "following_count": 1002,
        "following_tag_count": 4,
        "biography": "...",
        "biography_with_entities": {
            "raw_text": "...",
            "entities": []
        },
        "external_url": "",
        "total_igtv_videos": 0,
        "total_clips_count": 0,
        "total_ar_effects": 0,
        "usertags_count": 0,
        "is_favorite": false,
        "is_favorite_for_stories": false,
        "is_favorite_for_igtv": false,
        "is_favorite_for_highlights": false,
        "live_subscription_status": "default",
        "is_interest_account": false,
        "has_chaining": true,
        "hd_profile_pic_versions": [],
        "hd_profile_pic_url_info": {
            "url": "https://instagram.fyvr4-1.fna.fbcdn.net/...",
            "width": 1080,
            "height": 1080
        },
        "mutual_followers_count": 12,
        "profile_context": "Followed by ...",
        "profile_context_links_with_user_ids": [],
        "profile_context_mutual_follow_ids": [],
        "has_highlight_reels": true,
        "can_be_reported_as_fraud": false,
        "is_business": false,
        "account_type": 1,
        "professional_conversion_suggested_account_type": 2,
        "is_call_to_action_enabled": null,
        "personal_account_ads_page_name": null,
        "personal_account_ads_page_id": null,
        "include_direct_blacklist_status": true,
        "is_potential_business": false,
        "show_post_insights_entry_point": true,
        "is_bestie": true,
        "has_unseen_besties_media": false,
        "show_account_transparency_details": false,
        "show_leave_feedback": false,
        "robi_feedback_source": null,
        "auto_expand_chaining": false,
        "highlight_reshare_disabled": false,
        "is_memorialized": false,
        "open_external_url_with_in_app_browser": true
    }
```

This is the full JSON for user info query. I just don't see the benefits to add them to contacts since info like email, phone number are not there, people don't even use their real name on Instagram for that matter. Additionally, there is no way to query something like most active follower list. Without that, some people have hundreds of followers, and adding them all to contacts just does not make sense.

**Comment by huynhsontung** [comment]
I just realized adding contacts may enable Indirect to be used through system share card. In that sense it may actually worth looking into.

**Comment by huynhsontung** [comment]
Good news. My People support is added in version v1.4.0. Indirect will add ~40 most recent users to your contacts and you can pin it to your taskbar.

![image](https://user-images.githubusercontent.com/31434093/91823690-753e9180-ebee-11ea-9708-486969ea9aae.png)

**Comment by huynhsontung** [comment]
Store certification blocked me from using Contacts permission. Sending them an email did not help since they just copy and paste the same reply every time. Will revisit in the future.

**Comment by RokeJulianLockhart** [comment]
> Store certification blocked me from using Contacts permission. Sending them an email did not help since they just copy and paste the same reply every time. Will revisit in the future.

Those morons. I am thankful that you attempted the modifications that were requested regardless.

**Comment by xperiandri** [comment]
I will give you a contact who can help resolving the issue

**Comment by xperiandri** [comment]
@huynhsontung see request in LinkedIn

**Comment by xperiandri** [comment]
Were you managed to solve the issue?

**Comment by huynhsontung** [comment]
I did not. After Windows 11 was announced, I basically abandoned this feature entirely.

**Comment by RokeJulianLockhart** [comment]
Please reconsider addition. The rules of the Microsoft Store have been significantly relaxed recently to allow software that is less adherent to Microsoft' standards to be provided by the Microsoft Store and so that the Microsoft Store is able to install software via WinGet from its repositories, so they may not care anymore.

The features that are demonstrated by `http://github.com/huynhsontung/Indirect/issues/50#issuecomment-684531058` are useful, especially addition of many contacts to the Share-menu, which is solely being utilised more as time elapses.
