### ISSUE TITLE
"View profile" preview should be aligned to the right part of the screen

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#51]
Since the button is in the right part, it would make more sense to me

**Comment by lorisobi** [comment]
I think it is left because you can also click on the profile name instead of the button. i think the flyout should always be aligned to the button you clicked to open it

**Comment by huynhsontung** [comment]
@lorisobi got the idea. Since you can either click the button or the profile name to bring up the flyout, I decided to pin it under profile name since it's like an extension of profile name. Usually it's recommended to have flyout pops up on the button but I think in this case it's fine.

**Comment by MarcAnt01** [comment]
Then what's the point of having "view profile button"? Seems to redundant too me

**Comment by huynhsontung** [comment]
Because it's not obvious that's the profile name is clickable. I cannot make the profile name visually clickable either. It's redundant but so is the refresh button. It's there to let the user know it's possible.

**Comment by MarcAnt01** [comment]
OK, I'd suggest at this point to disable it on profile name and just use the "View profile" button

**Comment by huynhsontung** [comment]
I changed the flyout so that it now shows up where you clicked it
