### ISSUE TITLE
Add drag & drop

### ISSUE THREAD

**Issue by Kenya-West** [huynhsontung/Indirect#52]
Please add drag-and-drop feature for any opened chat.

Available file extensions (formats) should be:
- JPG/JPEG
- PNG
- GIF (will be treated as gif, not as picture)
- MP4 without sound (will be treated as gif, not as picture)
- Any other possible file (?)

Multiple files shall be sent one by one I guess,

Thanks!

**Comment by huynhsontung** [comment]
Thank you for the suggestion. Drag and drop for JPEG and PNG can be done but not GIF or MP4. Instagram only allows user to send their curated GIFs, all other image types will be converted to JPEG before sending.

**Comment by huynhsontung** [comment]
Drag and drop support for jpg/png files is added in version 1.2.2. Dropping files will directly send them without confirmation.
