### ISSUE TITLE
Can't display shared profile

### ISSUE THREAD

**Issue by MadafakinRio** [huynhsontung/Indirect#53]
When someone sends you a profile using the Share button in the app
![106588986_581873705854671_1223861695415138822_n](https://user-images.githubusercontent.com/26349936/86083732-595a2a80-ba9b-11ea-84d3-8677a992d911.jpg)
it can't be displayed because there's a special preview window.

Here's what Indirect shows
![image](https://user-images.githubusercontent.com/26349936/86083844-9d4d2f80-ba9b-11ea-9cea-0d5c0f3031ac.png)
and here's what should be shown
![image](https://user-images.githubusercontent.com/26349936/86083896-be158500-ba9b-11ea-995f-4bf024d64721.png)

**Comment by huynhsontung** [comment]
New item type 👀 I can fix it in the next update.

**Comment by huynhsontung** [comment]
Added support for profile share in version 1.2.1

![image](https://user-images.githubusercontent.com/31434093/86546459-dc3f1300-bee9-11ea-81ed-f520b3bf0802.png)
