### ISSUE TITLE
some link previews e.g. youtube links have unwrapped title in link preview

### ISSUE THREAD

**Issue by muznyo** [huynhsontung/Indirect#59]

**Comment by huynhsontung** [comment]
This was unintended and me being too lazy to fix it 😬 Fixed in 1.2.1.

**Comment by muznyo** [comment]
Still not fixed for me, same issue

**Comment by huynhsontung** [comment]
Hmm are you sure you are running the latest version (1.2.1)?

**Comment by muznyo** [comment]
Yes, running version v1.2.1

**Comment by huynhsontung** [comment]
Ah sorry I misread the issue. The preview title is unwrapped, not the link itself. Will be fixed in next update 😅

**Comment by huynhsontung** [comment]
This should be fixed in version 1.2.2
