### ISSUE TITLE
Cleaning up voice messages

### ISSUE THREAD

**Issue by MadafakinRio** [huynhsontung/Indirect#61]
The media player for voice messages looks a bit off.
![image](https://user-images.githubusercontent.com/26349936/86520304-08538900-be43-11ea-9336-28dae9d6a2e4.png)
The buttons and the seek bar aren't aligned. Looks like you've set the play button to be a bit higher than the rest.
Also I'm not sure how useful the 'Cast to device button' is in this case. Maybe hide it? That would give a bit of space to the seek bar which is tiny now and barely usable.

**Comment by MarcAnt01** [comment]
I'd suggest to completely replace this UI with something that looks better

**Comment by huynhsontung** [comment]
The current media player control has UWP default styling and I was actually surprised that it looks that bad. Styling media player is extremely painful but at least I got it to look a bit more consistent. Let me know what you think.

![](https://i.imgur.com/u1m9sqb.gifv)

**Comment by MarcAnt01** [comment]
Definitely better but I'd rather have something that looks more similar to Instagram Directs UI (volume control is useless)
![image](https://user-images.githubusercontent.com/43090263/86572366-23bdb180-bf73-11ea-9f71-d6ea26ac3a73.png)

**Comment by MadafakinRio** [comment]
It's way better now, thanks!
