### ISSUE TITLE
Replace Segoe MDL2 icons with Fluent design icons

### ISSUE THREAD

**Issue by muznyo** [huynhsontung/Indirect#71]
https://github.com/yoshiask/FluentSystemIconsUWP

**Comment by huynhsontung** [comment]
Oh interesting. I will look into it.

**Comment by MarcAnt01** [comment]
@muznyo are those asset meant to be used for uwp apps? I knew their targets were Android, iOS and web

**Comment by muznyo** [comment]
Some uwp app developers already implemented them, it's already in files uwp beta app

**Comment by MarcAnt01** [comment]
Yeah, I have seen that, but am not sure it is the right choice currently

**Comment by huynhsontung** [comment]
Fluent icons are part of the system font in Windows 11. For simplicity, Indirect will stick with that.
