### ISSUE TITLE
IGTV videos aren't supported

### ISSUE THREAD

**Issue by MadafakinRio** [huynhsontung/Indirect#79]
Similar to my last issue, IGTV videos can't be displayed ('Content type is not yet supported.') when shared directly (not as a link).

This is what is looks like on the web:
![image](https://user-images.githubusercontent.com/26349936/94282030-a68d5180-ff4f-11ea-90dc-453f7d51d6c4.png)

**Comment by huynhsontung** [comment]
This feature is added in version 1.5.0. Clicking the item will open the post on your web browser.

![image](https://user-images.githubusercontent.com/31434093/104386857-cccd0200-54ea-11eb-82a0-c02896b96ddc.png)
