### ISSUE TITLE
Add emoji icon to the chat!

### ISSUE THREAD

**Issue by aimproxy** [huynhsontung/Indirect#82]
Before anything, a big thanks for u guys who develop this incredible application, since Instagram doesn't seem to care about its own desktop application, this app is the perfect replacement!

About my issue, could we add the emoji icon for the text box field on chat?
How can I help u guys, can I handle this my own, and I make a PR?

Thx

**Comment by huynhsontung** [comment]
You can definitely make your own PR and contribute to the project. I would greatly appreciate it!
Regarding the issue, user can already insert emoji using Windows' emoji panel (`Win + .`) but I can see many users are not aware of this. We can either have a button to manually trigger this panel open for the chat box or make our own custom emoji panel. The first approach is more flexible and less work on our end but the latter may give us more customizations. Let me know if you have any problems understanding the existing code.

**Comment by huynhsontung** [comment]
This feature is added in version 1.5.0. Closing.
