### ISSUE TITLE
Wrong device in "Security -> Signed From" page

### ISSUE THREAD

**Issue by Kenya-West** [huynhsontung/Indirect#86]
I went to Settings -> Security -> Signed From section (dunno how it is named in english, though) and I see that inDirect app shows as Samsung SM-G930F. This is wrong because I have signed from my PC with name "KW-PC".

![image](https://user-images.githubusercontent.com/12271104/104810178-74716980-5836-11eb-929b-753eca6539a9.png)

Please make inDirect passing correct device name.

**Comment by huynhsontung** [comment]
This is expected behavior as Indirect masks itself as an Android phone when talking with the Instagram server.
