### ISSUE TITLE
UI issues 

### ISSUE THREAD

**Issue by LorisTecnology** [huynhsontung/Indirect#89]
Is a great app
but i don't think is actually usable now

sometime UI doesn't actually works cause doesn't update the active chat

**Comment by huynhsontung** [comment]
Can you provide more information regarding this problem? There is a known issue that a chat thread with a Facebook user will not update on changes. Can you verify if the problem exists on non-Facebook threads?

**Comment by LorisTecnology** [comment]
when i click on a chat the UI doesn't update accordingly

**Comment by huynhsontung** [comment]
Can you elaborate on how the UI does not update accordingly? Do you click a chat on the left pane but nothing shows up on the right pane? Or it does show up but something looks wrong?
