### ISSUE TITLE
Facebook login

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#9]
The app lacks the possibility to login for who has created their Instragram account through Facebook

**Comment by huynhsontung** [comment]
Yes this is something I have wanted to tackle for a while. Since the app is replicating Instagram client, I will need to copy Instagram's FB OAuth over. I am not sure how long it will take but fret not I am on it 😁

**Comment by MarcAnt01** [comment]
> Yes this is something I have wanted to tackle for a while. Since the app is replicating Instagram client, I will need to copy Instagram's FB OAuth over. I am not sure how long it will take but fret not I am on it 😁

Using the same login method as Facebook Osmeta app would be great, but don't know if there are public APIs for that.
It basically opened the browser on Facebook and then opened the app, so that I didn't even need to  insert mail and password.

**Comment by huynhsontung** [comment]
Feature added in 74aa10f653dbc465c37ecfce0a3dea22c775a756

**Comment by MarcAnt01** [comment]
Thank you
