### ISSUE TITLE
{Question} Can it run on Windows 8.1

### ISSUE THREAD

**Issue by Suleman-Elahi** [huynhsontung/Indirect#94]
Can I run this on Windows 8.1?
If yes, can mention the steps?

**Comment by huynhsontung** [comment]
No, Indirect would not run on Windows 8.1. The app depends on a lot of APIs and third-party modules that are only available to Windows 10 Build 10.0.17134 and up. Supporting earlier versions of Windows 10 (and potentially Windows 8.1) is technically possible but would involve a massive amount of refactoring.
