### ISSUE TITLE
More subtle acrylic in the sidebar

### ISSUE THREAD

**Issue by lorisobi** [huynhsontung/Indirect#96]
Mica material is coming and the sidebar of Indirect is just made for this.
But till then i found the Acrylic transparency currently used, to be a bit to strong and sometimes distracting.

In my view Indirect could switch to a more subtle acrylic in the sidebar

**Comment by huynhsontung** [comment]
There is currently a WinUI bug that can make the default Acrylic brighter than it should be on some machines. The Acrylic that Indirect uses as background should be legible even in a bright background (and just a bit brighter compared to Mica). I can tune the Acrylic so it is more in line with Mica in the next update.

Indirect on Windows 11 is already using Mica as a replacement for all Acrylic backgrounds 😉
