### ISSUE TITLE
Any other method to install this App?

### ISSUE THREAD

**Issue by IndraTensei** [huynhsontung/Indirect#97]
Windows store doesn't work on my System, is there any other way to install this application?
Sorry for the trouble.

**Comment by huynhsontung** [comment]
You can always clone the repo and build it from the source. Windows Store is the only distribution method, unfortunately.

**Comment by IndraTensei** [comment]
> You can always clone the repo and build it from the source. Windows Store is the only distribution method, unfortunately.

Thank you for the quick response.
Sorry I am new to this, can you send me some reference on how to build it if possible!

**Comment by huynhsontung** [comment]
If you only want to be able to run the app, I would strongly recommend against building the app yourself since you would need to download GBs of developer tools and components. You would also have to enable Developer Mode on your machine which might not always be possible.

You can try sideloading the app using the link below. Simply download, extract, then run `Install.ps1` and the app will be installed. I have not tried this method before so let me know if you encounter any problems.

https://1drv.ms/u/s!AnXKNwU_ded0jYgyO82mT-Wo7RyGaw?e=kKJY5C

**Comment by IndraTensei** [comment]
> If you only want to be able to run the app, I would strongly recommend against building the app yourself since you would need to download GBs of developer tools and components. You would also have to enable Developer Mode on your machine which might not always be possible.
> 
> You can try sideloading the app using the link below. Simply download, extract, then run `Install.ps1` and the app will be installed. I have not tried this method before so let me know if you encounter any problems.
> 
> https://1drv.ms/u/s!AnXKNwU_ded0jYgyO82mT-Wo7RyGaw?e=kKJY5C

I ran Install.ps1 through the powershell and it gave me this error that running script is disabled.
&emsp;![image](https://user-images.githubusercontent.com/69427966/134131927-0eeb774e-3983-4230-ab5c-c4d65e64d9dc.png)

- Then gone through the link [https://go.microsoft.com/fwlink/?LinkID=135170](url) they referred 
- Changed my Execution_Policy from **Default** to **Remote Signed** through the command 
`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned` in powershell. 
- Installed 'Install.ps1' then the app was installed.

The app is working fine with no issue, Thank you for the help.
If you are still working in this project I have some suggestion for the app, to make it minimize the app to tray when we close the app and have a push notification on every messages.

Again Thank you for the help!

**Comment by huynhsontung** [comment]
Glad to hear the installer works for you. Please note that the app will not update automatically using this method. 

For the notification, Indirect already has push notification without having to minimize to app tray. You can close the app and still receive message notifications. This is one of the advantages of being a UWP app. 😄

**Comment by huynhsontung** [comment]
Oh shoot, I just realized I sent you a Debug build. You may receive random debug notifications every hour or so. If you encounter this please uninstall that version and install this one instead.

https://1drv.ms/u/s!AnXKNwU_ded0jYgzbx3Bq7GG_N_Iqg?e=kLKOiA

**Comment by IndraTensei** [comment]
> Oh shoot, I just realized I sent you a Debug build. You may receive random debug notifications every hour or so. If you encounter this please uninstall that version and install this one instead.
> 
> https://1drv.ms/u/s!AnXKNwU_ded0jYgzbx3Bq7GG_N_Iqg?e=kLKOiA

Yh a push notification about socket was popping out now and then.
Thanks for the dl link.
